# z64rom toml patch macros
@zero4                     = 00000000
@zero8                     = zero4 zero4
@audio_heap_size           = 0xBC1864
@audio_init_pool_size      = 0xBC1868
@audio_permanent_pool_size = 0xBC186C

# SpeedUP: Stop Writing AB To Empty RAM Slots
0x00B74FE0 = zero4
0x00B75094 = zero4

# SpeedUP: Remove printf Debug Function
0x00002CF0 = 03E00008
0x00002CF8 = zero4

# SpeedUP: Remove the Exception Handler On osStartThread
0x00C09D78 = 0x1000

# Faster Boot Loading(For RAM) & Extended RAM
0x00005DFC = AFA10008
0x00005E00 = zero4

# Subscreen Delay Fix
0x00B36B6B = 03
0x00B3A994 = zero4

# Crash Debugger: Disable Button Combo
0x00B4C55C = 03E00008 zero8 zero8

# NOP AudioDebug_Draw
0x00B65BF0 = 03E00008 zero8 zero4

# vanilla values
audio_heap_size           = 00037F00
audio_init_pool_size      = 0000E0E0
audio_permanent_pool_size = 0000BCE0