# z64rom toml patch macros
@zero4                     = 00000000
@zero8                     = zero4 zero4
@audio_heap_size           = 0xBC1864
@audio_init_pool_size      = 0xBC1868
@audio_permanent_pool_size = 0xBC186C

[rom/system/static/z_boot.bin]
    reloc_from = 0x00001060
    # SpeedUP: Remove printf Debug Function
    0x00002CF0 = 03E00008
    0x00002CF8 = zero4

    # Faster Boot Loading(For RAM) & Extended RAM
    0x00005DFC = AFA10008
    0x00005E00 = zero4

[rom/system/static/z_code.bin]
    reloc_from = 0x00A94000
    # SpeedUP: Stop Writing AB To Empty RAM Slots
    0x00B74FE0 = zero4
    0x00B75094 = zero4

    # Subscreen Delay Fix
    0x00B3A994 = zero4 # NULL jal func_800C2500 in PreRender_Calc

    # Crash Debugger: Disable Button Combo
    0x00B4C55C = 03E00008 zero8 zero8

    # NOP AudioDebug_Draw
    0x00B65BF0 = 03E00008 zero8 zero4

    # vanilla values
    audio_heap_size           = 00040000
    audio_init_pool_size      = 00012160
    audio_permanent_pool_size = 0000FD60

[rom/system/kaleido/0x01-Player/overlay.zovl]
    # SpeedUP: Player GI Thing
    0x00008CC8 = 0x1000
    
    # func_8084FCAC
    # Camera_ChangeMode(Play_GetCamera(playState, CAM_ID_MAIN), XXXX);
    0x0001DB34 = 0x....0001 # CAM_MODE_TARGET

[rom/actor/0x00FF-Push_Block/actor.zovl]
    # Push Max Speed
    0x11EE = 0x4080 # 0000 == 4.0f
    # Push Accel
    0x1202 = 0x3f80 # 0000 == 1.0f
    # Timer
    0x138E = 0x0004