# # Patch rom header  # # # # # # # # # # # # # # # # # # # # # # # # #
#   More info about header in https://n64brew.dev/wiki/ROM_Header     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# z64rom toml patch macros
@zero4            = 0x00000000
@zero8            = zero4 zero4
@header_name      = 0x20
@header_media_fmt = 0x3B
@header_game_id   = 0x3C
@header_region    = 0x3E
@header_revision  = 0x3F

# clear rom name before patching new name
header_name      = zero8 zero8 zero8 0x000000

# max 20 characters
header_name      = "z64romhack"
header_media_fmt = "C"
header_game_id   = "ZL"
header_region    = "E"
header_revision  = 0x00

# You can also patch files into addresses
# 0x3FFFFF0 = FILE("deadbeef.bin")