{ "Hyrule Field", Select_LoadGame, ENTR_SPOT00_0 },
{ "Kakariko Village", Select_LoadGame, ENTR_SPOT01_0 },
{ "Graveyard", Select_LoadGame, ENTR_SPOT02_0 },
{ "Zora's River", Select_LoadGame, ENTR_SPOT03_0 },
{ "Kokiri Forest", Select_LoadGame, ENTR_SPOT04_0 },
{ "Sacred Forest Meadow", Select_LoadGame, ENTR_SPOT05_0 },
{ "Lake Hylia", Select_LoadGame, ENTR_SPOT06_0 },
{ "Zora's Domain", Select_LoadGame, ENTR_SPOT07_0 },
{ "Zora's Fountain", Select_LoadGame, ENTR_SPOT08_0 },
{ "Gerudo Valley", Select_LoadGame, ENTR_SPOT09_0 },
{ "Lost Woods", Select_LoadGame, ENTR_SPOT10_0 },
{ "Desert Colossus", Select_LoadGame, ENTR_SPOT11_0 },
{ "Gerudo's Fortress", Select_LoadGame, ENTR_SPOT12_0 },
{ "Haunted Wasteland", Select_LoadGame, ENTR_SPOT13_0 },
{ "Hyrule Castle", Select_LoadGame, ENTR_SPOT15_0 },
{ "Death Mountain Trail", Select_LoadGame, ENTR_SPOT16_0 },
{ "Death Mountain Crater", Select_LoadGame, ENTR_SPOT17_0 },
{ "Goron City", Select_LoadGame, ENTR_SPOT18_0 },
{ "Lon Lon Ranch", Select_LoadGame, ENTR_SPOT20_0 },
{ "Temple Of Time", Select_LoadGame, ENTR_TOKINOMA_0 },
{ "Chamber of the Sages", Select_LoadGame, ENTR_KENJYANOMA_0 },
{ "Shooting Gallery", Select_LoadGame, ENTR_SYATEKIJYOU_0 },
{ "Hyrule Garden Minigame", Select_LoadGame, ENTR_HAIRAL_NIWA_0 },
{ "Grave (Redead)", Select_LoadGame, ENTR_HAKAANA_0 },
{ "Grave (Fairy's Fountain)", Select_LoadGame, ENTR_HAKAANA2_0 },
{ "Royal Family's Tomb", Select_LoadGame, ENTR_HAKAANA_OUKE_0 },
{ "Great Fairy's Fountain (Upgrades)", Select_LoadGame, ENTR_DAIYOUSEI_IZUMI_0 },
{ "Fairy's Fountain (Healing Fairies)", Select_LoadGame, ENTR_YOUSEI_IZUMI_TATE_0 },
{ "Great Fairy's Fountain (Spells)", Select_LoadGame, ENTR_YOUSEI_IZUMI_YOKO_0 },
{ "Battle With Ganon", Select_LoadGame, ENTR_GANON_FINAL_0 },
{ "Castle Courtyard", Select_LoadGame, ENTR_NAKANIWA_0 },
{ "Fishing Pond", Select_LoadGame, ENTR_TURIBORI_0 },
{ "Bombchu Bowling Alley", Select_LoadGame, ENTR_BOWLING_0 },
{ "Talon's House", Select_LoadGame, ENTR_SOUKO_0 },
{ "Ranch Silo", Select_LoadGame, ENTR_SOUKO_1 },
{ "Guard House", Select_LoadGame, ENTR_MIHARIGOYA_0 },
{ "Granny's Potion Shop", Select_LoadGame, ENTR_MAHOUYA_0 },
{ "Treasure Chest Game", Select_LoadGame, ENTR_TAKARAYA_0 },
{ "House of Skulltula", Select_LoadGame, ENTR_KINSUTA_0 },
{ "Market Entrance", Select_LoadGame, ENTR_ENTRA_0 },
{ "Market", Select_LoadGame, ENTR_MARKET_DAY_0 },
{ "Back Alley", Select_LoadGame, ENTR_MARKET_ALLEY_0 },
{ "Temple of Time Exterior", Select_LoadGame, ENTR_SHRINE_0 },
{ "Link's House", Select_LoadGame, ENTR_LINK_HOME_0 },
{ "Carpenter Boss's House", Select_LoadGame, ENTR_KAKARIKO_0 },
{ "Back Alley House (Man in Green)", Select_LoadGame, ENTR_KAKARIKO3_0 },
{ "Know-It-All Brothers' House", Select_LoadGame, ENTR_KOKIRI_HOME_0 },
{ "Twins' House", Select_LoadGame, ENTR_KOKIRI_HOME3_0 },
{ "Mido's House", Select_LoadGame, ENTR_KOKIRI_HOME4_0 },
{ "Saria's House", Select_LoadGame, ENTR_KOKIRI_HOME5_0 },
{ "Stable", Select_LoadGame, ENTR_MALON_STABLE_0 },
{ "Gravekeeper's Hut", Select_LoadGame, ENTR_HUT_0 },
{ "Back Alley House", Select_LoadGame, ENTR_IMPA_0 },
{ "Impa's House", Select_LoadGame, ENTR_LABO_0 },
{ "Lakeside Laboratory", Select_LoadGame, ENTR_HYLIA_LABO_0 },
{ "Carpenters' Tent", Select_LoadGame, ENTR_TENT_0 },
{ "Bazaar", Select_LoadGame, ENTR_SHOP1_0 },
{ "Kokiri Shop", Select_LoadGame, ENTR_KOKIRI_SHOP_0 },
{ "Goron Shop", Select_LoadGame, ENTR_GOLON_0 },
{ "Zora Shop", Select_LoadGame, ENTR_ZOORA_0 },
{ "Kakariko Potion Shop", Select_LoadGame, ENTR_DRAG_0 },
{ "Market Potion Shop", Select_LoadGame, ENTR_ALLEY_SHOP_0 },
{ "Bombchu Shop", Select_LoadGame, ENTR_NIGHT_SHOP_0 },
{ "Happy Mask Shop", Select_LoadGame, ENTR_FACE_SHOP_0 },
{ "Gerudo Training Ground", Select_LoadGame, ENTR_MEN_0 },
{ "Inside the Deku Tree", Select_LoadGame, ENTR_YDAN_0 },
{ "Gohma's Lair", Select_LoadGame, ENTR_YDAN_BOSS_0 },
{ "Dodongo's Cavern", Select_LoadGame, ENTR_DDAN_0 },
{ "King Dodongo's Lair", Select_LoadGame, ENTR_DDAN_BOSS_0 },
{ "Inside Jabu-Jabu's Belly", Select_LoadGame, ENTR_BDAN_0 },
{ "Barinade's Lair", Select_LoadGame, ENTR_BDAN_BOSS_0 },
{ "Forest Temple", Select_LoadGame, ENTR_BMORI1_0 },
{ "Phantom Ganon's Lair", Select_LoadGame, ENTR_MORIBOSSROOM_0 },
{ "Bottom of the Well", Select_LoadGame, ENTR_HAKADANCH_0 },
{ "Shadow Temple", Select_LoadGame, ENTR_HAKADAN_0 },
{ "Bongo Bongo's Lair", Select_LoadGame, ENTR_HAKADAN_BS_0 },
{ "Fire Temple", Select_LoadGame, ENTR_HIDAN_0 },
{ "Volvagia's Lair", Select_LoadGame, ENTR_FIRE_BS_0 },
{ "Water Temple", Select_LoadGame, ENTR_MIZUSIN_0 },
{ "Morpha's Lair", Select_LoadGame, ENTR_MIZUSIN_BS_0 },
{ "Spirit Temple", Select_LoadGame, ENTR_JYASINZOU_0 },
{ "Iron Knuckle's Lair", Select_LoadGame, ENTR_JYASINBOSS_0 },
{ "Twinrova's Lair", Select_LoadGame, ENTR_JYASINBOSS_2 },
{ "Ganon's Tower", Select_LoadGame, ENTR_GANON_0 },
{ "Ganondorf's Lair", Select_LoadGame, ENTR_GANON_BOSS_0 },
{ "Ice Cavern", Select_LoadGame, ENTR_ICE_DOUKUTO_0 },
{ "Dampé's Grave", Select_LoadGame, ENTR_HAKASITARELAY_0 },
{ "Inside Ganon's Castle", Select_LoadGame, ENTR_GANONTIKA_0 },
{ "Ganondorf's Death Scene & Tower Escape Exterior", Select_LoadGame, ENTR_GANON_DEMO_0 },
{ "Escaping Ganon's Tower 1", Select_LoadGame, ENTR_GANON_SONOGO_0 },
{ "Escaping Ganon's Tower 2", Select_LoadGame, ENTR_GANON_SONOGO_2 },
{ "Escaping Ganon's Tower 3", Select_LoadGame, ENTR_GANON_SONOGO_4 },
{ "Escaping Ganon's Tower 4", Select_LoadGame, ENTR_GANON_SONOGO_6 },
{ "Escaping Ganon's Castle", Select_LoadGame, ENTR_GANONTIKA_SONOGO_0 },
{ "Thieves' Hideout 1", Select_LoadGame, ENTR_GERUDOWAY_0 },
{ "Thieves' Hideout 2", Select_LoadGame, ENTR_GERUDOWAY_2 },
{ "Thieves' Hideout 3", Select_LoadGame, ENTR_GERUDOWAY_4 },
{ "Thieves' Hideout 4", Select_LoadGame, ENTR_GERUDOWAY_6 },
{ "Thieves' Hideout 5", Select_LoadGame, ENTR_GERUDOWAY_10 },
{ "Thieves' Hideout 6", Select_LoadGame, ENTR_GERUDOWAY_12 },
{ "Grotto 0 - Gossip Stone & Chest", Select_LoadGame, ENTR_KAKUSIANA_0 },
{ "Grotto 1 - Skulltula & Gold Skulltula", Select_LoadGame, ENTR_KAKUSIANA_1 },
{ "Grotto 2 - Business Scrub & Heart Piece", Select_LoadGame, ENTR_KAKUSIANA_2 },
{ "Grotto 3 - Redeads", Select_LoadGame, ENTR_KAKUSIANA_3 },
{ "Grotto 4 - 3 Business Scrubs", Select_LoadGame, ENTR_KAKUSIANA_4 },
{ "Grotto 5 - Gossip Stone, Skulltula, Cow", Select_LoadGame, ENTR_KAKUSIANA_5 },
{ "Grotto 6 - Octorok", Select_LoadGame, ENTR_KAKUSIANA_6 },
{ "Grotto 7 - Business Scrub & Deku Nut Upgrade", Select_LoadGame, ENTR_KAKUSIANA_7 },
{ "Grotto 8 - 2 Wolfos", Select_LoadGame, ENTR_KAKUSIANA_8 },
{ "Grotto 9 - Bombable Walls", Select_LoadGame, ENTR_KAKUSIANA_9 },
{ "Grotto 10 - 2 Business Scrubs", Select_LoadGame, ENTR_KAKUSIANA_10 },
{ "Grotto 11 - Tektite & Heart Piece", Select_LoadGame, ENTR_KAKUSIANA_11 },
{ "Grotto 12 - Deku Stage", Select_LoadGame, ENTR_KAKUSIANA_12 },
{ "Grotto 13 - Rupees & Cow", Select_LoadGame, ENTR_KAKUSIANA_13 },
{ "Cutscene Map", Select_LoadGame, ENTR_HIRAL_DEMO_0 },
{ "Ganondorf Test Room", Select_LoadGame, ENTR_BESITU_0 },
{ "Sasa Test", Select_LoadGame, ENTR_SASATEST_0 },
{ "Jungle Gym", Select_LoadGame, ENTR_TEST01_0 },
{ "Treasure Chest Room", Select_LoadGame, ENTR_TESTROOM_0 },
{ "Stalfos Miniboss Room", Select_LoadGame, ENTR_SYOTES_0 },
{ "Stalfos Boss Room", Select_LoadGame, ENTR_SYOTES2_0 },
{ "Sutaru", Select_LoadGame, ENTR_SUTARU_0 },
{ "Shooting Gallery", Select_LoadGame, ENTR_TEST_SYATEKIJYOU_0 },
{ "Depth Test", Select_LoadGame, ENTR_DEPTH_TEST_0 },
{ "Early Hyrule Garden Game", Select_LoadGame, ENTR_HAIRAL_NIWA2_0 },
