#include "z64rom.h"

const char* gOoT_Object[] = {
	"Empty",
	"GamePlay_Global",
	"GamePlay_Field",
	"GamePlay_Dungeon",
	"Empty",
	"Empty",
	"Aria",
	"Octorok",
	"Guay",
	"Poe",
	"Great_Fairy",
	"Floormaster_&_Wallmaster",
	"Dodongo",
	"Keese",
	"Treasure_Chest",
	"Dancing_Flame",
	"Empty",
	"Empty",
	"Shabom",
	"Cucco",
	"Adult_Link",
	"Child_Link",
	"Tektites",
	"Leever",
	"Peahat",
	"King_Dodongo",
	"Epona",
	"Lizalfos_&_Dinolfos",
	"Gohma",
	"Child_Zelda",
	"Gohma_Larva",
	"Baby_Dodongo",
	"Dark_Link",
	"Biri",
	"Tailpasaran",
	"Kakariko_Rooftop_Man",
	"Skulltulas",
	"Torch_Slug",
	"Stingers",
	"Generic_Horse",
	"Bazaar_Proprietor",
	"NPC_Animations_I",
	"Kokiri_Forest_Objects",
	"Dodongos_Cavern_Objects",
	"Fire_Temple_Objects",
	"Ganondorfs_Horse",
	"Zora",
	"Hyrule_Field_Objects_Child",
	"Moblins",
	"Bomb_Flower",
	"Stalfos",
	"Mido_I",
	"NPC_Animations_II",
	"RedHaired_Kokiri_Girl",
	"Inside_the_Deku_Tree_Objects",
	"Phantom_Ganon",
	"Armos",
	"Deku_Babas",
	"Empty",
	"Impas_Masked_Head",
	"Laughing_Man",
	"Hylian_Woman_in_Purple_Dress",
	"Hylian_Man_in_Blue_Shirt_&_Orange_Pants",
	"Hylian_Woman_in_White_Shirt_&_Orange_Pants",
	"JabuJabu",
	"Old_Hylian_Man",
	"Old_Hylian_Mans_Head",
	"Hylian_Man_in_Purple_Shirt_&_Green_Pants",
	"Carpenter_Bosss_Wife",
	"Hylian_Woman_in_Blue_Shirt_&_White_Dress",
	"Zeldas_Horse",
	"Opening_Cutscene_Animations",
	"Warp_Circle_&_Rupee_Prism",
	"Heart_Container",
	"Mad_Scrub",
	"Saria",
	"RedHaired_Kokiri_Boy_I",
	"Gerudo_Training_Ground_Objects",
	"Fado",
	"Kokiri_Girl_in_Brown_Bands_Head",
	"Kokiri_Boy_in_Green_Caps_Head",
	"Kokiri_Girl_in_Green_Bands_Head",
	"Kokiri_Boy_in_Mint_Caps_Head",
	"Kokiri_Shop_Proprietors_Head",
	"Kokiri_Girl_in_Green_Caps_Head",
	"Fados_Head",
	"Bari",
	"Soldier",
	"Soldier_Courtyard",
	"Water_Temple_Objects",
	"Phantom_Ganons_Horse_&_Objects",
	"Shooting_Gallery_&_Bazaar_Proprietors",
	"Forest_Temple_Room_13_Twisted",
	"Bubbles",
	"Temple_of_Time_Objects",
	"Flying_Floor_Tile",
	"Adult_Zelda",
	"Warp_Pad_Base",
	"Light_Warp_Pad",
	"Shadow_Warp_Pad",
	"Fire_Warp_Pad",
	"Water_Warp_Pad",
	"Spirit_Warp_Pad",
	"Forest_Warp_Pad",
	"Ocarina_Pedestal",
	"Shadow_Temple_Objects",
	"Lake_Hylia_Objects",
	"Ice_Cavern_Objects",
	"Dampes_Relay_Race_Objects",
	"Big_Poe_&_Poe_Guide",
	"Sharp_&_Flat",
	"Forest_Temple_Room_13_Straight",
	"Forest_Temple_Room_14_Straight",
	"Forest_Temple_Room_14_Twisted",
	"Forest_Temple_Objects",
	"Forest_Temple_Textures",
	"Zoras_Fountain_Objects",
	"Empty",
	"Flagpole",
	"Brown_Bird",
	"Empty",
	"Empty",
	"Empty",
	"Empty",
	"Bushes_&_Trees",
	"Empty",
	"Empty",
	"Empty",
	"Empty",
	"Rectangular_Stone_Blocks_Light_Grey",
	"Rectangular_Stone_Blocks_Dark_Grey",
	"Empty",
	"Empty",
	"Blade_Trap",
	"Orange_Pot",
	"Impa",
	"Talon",
	"Dampe_&_Ghost",
	"Sheik",
	"Beamos",
	"Barinade",
	"Bottom_of_the_Well_Objects",
	"TODO",
	"Goddesses_Flame_of_Creation",
	"Empty",
	"Goddess_Light_Dome",
	"Light_Beam_&_Rubble",
	"Golden_Goddesses",
	"JaggedEdged_Light_Ring",
	"Triforce_&_Beam_of_Light",
	"Inside_JabuJabus_Belly_Objects",
	"Soldiers",
	"Redead_&_Gibdo",
	"Poe_Sisters_&_Objects",
	"Golden_Gauntlets_Boulder",
	"Ganondorf_Cutscenes",
	"Volvagia_Flying",
	"Darunia",
	"Flare_Dancer",
	"Medallions",
	"Child_Epona",
	"Graveyard_Objects",
	"Gravestone",
	"Child_Ruto",
	"Torches",
	"Volvagia_WhackaMole",
	"Dead_Hand_&_Hands",
	"Rauru",
	"Time_Block_Disappearance_Effect",
	"Empty",
	"Item_Model_Small_Key",
	"Mirror_Shields_Light_Reflection",
	"Jelly_Platform",
	"Item_Model_Spiritual_Stones",
	"Gerudo_Valley_Objects",
	"Goron_City_Objects",
	"Boss_Doors",
	"Death_Mountain_Crater_Objects",
	"Shop_Shelves",
	"Nabooru",
	"Morpha",
	"Shellblade",
	"Item_Model_Music_Notes",
	"Item_Model_Recovery_Heart",
	"Item_Model_Compass",
	"Item_Model_Big_Key",
	"Item_Model_Medallions",
	"Item_Model_Deku_Nut",
	"Saria",
	"Item_Model_Heart_Container_&_Piece_of_Heart",
	"Item_Model_Quivers",
	"Item_Model_Bomb_Bags",
	"Ingo",
	"Kotake_&_Koume",
	"Death_Mountain_Trail_Objects",
	"Mido_II",
	"RedHaired_Kokiri_Boy_II",
	"NPC_Animations_III",
	"Item_Model_Empty_Bottle",
	"Item_Model_Deku_Stick",
	"Item_Model_Dungeon_Map_&_Stone_of_Agony",
	"Goron_Medigoron_Biggoron",
	"Adult_Ruto",
	"Item_Model_Deku_Shield",
	"Deku_Tree_Sprout",
	"Item_Model_Magic_Jars",
	"Item_Model_Bomb",
	"Goron",
	"Adult_Malon",
	"Item_Model_Wallets",
	"Ingos_Horse_&_Archery_Range_Horse",
	"Twinrova",
	"Like_Like",
	"Parasitic_Tentacle_&_Tentacle_Obstruction",
	"Anubis_&_Fire_Trap",
	"Item_Model_Gerudo_Card",
	"Item_Model_Arrows",
	"Item_Model_Bombchu",
	"Item_Model_Pocket_&_Weird_Eggs",
	"Item_Model_Silver_&_Golden_Scales",
	"Item_Model_Hylian_Shield",
	"Item_Model_Hookshot_&_Longshot",
	"Item_Model_Ocarina_of_Time",
	"Item_Model_Lon_Lon_Milk",
	"Child_Malon",
	"Ganondorf_Boss",
	"Bongo_Bongo",
	"Spike_Trap_[Duplicate]",
	"Empty",
	"Spike_Trap",
	"Frog",
	"Item_Model_Fairy_Slingshot",
	"Item_Model_Boomerang",
	"Item_Model_Fairy_Bow",
	"Item_Model_Lens_of_Truth",
	"Item_Model_Potions",
	"Kakariko_Rooftop_Man",
	"Chamber_of_the_Sages_Cutscene_Objects",
	"Item_Model_Mirror_Shield",
	"Item_Model_Zeldas_Letter",
	"Hyrule_Castle_Objects",
	"Spirit_Temple_Objects",
	"Item_Model_Tunics",
	"Item_Model_Magic_Bean",
	"Item_Model_Fish",
	"Item_Model_Poachers_Saw",
	"Item_Model_Megaton_Hammer",
	"Item_Model_Reed_Whistle",
	"Item_Model_Giants_Knife_&_Biggorons_Sword",
	"Kakariko_Village_Objects_Shared",
	"Mido_[Duplicate]",
	"Mido",
	"RedHaired_Kokiri_Boy",
	"RedHaired_Kokiri_Girl",
	"Zora",
	"King_Zora",
	"HorseJumping_Fence",
	"Kokiri_Shop_Proprietor_Animations",
	"Kokiri_Shop_Proprietors_Head",
	"Goron_Shop_Proprietor_Animations",
	"Zora_Shop_Proprietor_Animations",
	"Dog_Lady",
	"Iron_Knuckle",
	"Hylian_Men_I",
	"Young_Hylian_Women",
	"Item_Model_Cuccos",
	"Skull_Kid",
	"Item_Model_Rutos_Letter",
	"Old_Hylian_Men",
	"Old_Hylian_Woman",
	"Item_Model_Fairy_Ocarina",
	"Potion_Shop_Granny",
	"Cucco_Lady",
	"Hylian_Men_II",
	"Zoras_River_Objects",
	"Zoras_Domain_Objects",
	"Freezard",
	"Carpenter_Bosss_Wife",
	"Gerudo_in_White",
	"Minigame_Points",
	"Item_Model_Iron_Boots",
	"Item_Model_Deku_Seeds",
	"Ganondorfs_Magic_Blast",
	"Stone_Elevator_Pillar",
	"Hookshot_Pillar_&_Wall_Target",
	"Stone_Moving_Deku_Tree_Platform",
	"Magic_Bean_Objects",
	"Rolling_Boulder",
	"Empty",
	"Carpenter_Boss",
	"Carpenters",
	"Empty",
	"Cucco_Chick",
	"Dark_Links_Illusion_Room",
	"Medigoron_Animations",
	"Magic_Bean_Seller",
	"Carpenter_Bosss_Son",
	"Ingos_Ranch_Gate",
	"Sun_Switch",
	"Grass",
	"Pot",
	"Item_Model_Silver_&_Golden_Gauntlets",
	"Item_Model_N_Coins",
	"Square_Signpost",
	"Ganons_Castle_Exterior_Objects",
	"Kaepora_Gaebora",
	"Lake_Scientist",
	"Windmill_Man",
	"Item_Model_Keaton_Mask",
	"Item_Model_Redead_Mask",
	"Item_Model_Spooky_Mask",
	"Item_Model_Bunny_Hood",
	"Item_Model_Mask_of_Truth",
	"Ganons_Tower_Objects",
	"Water_Spout_Small",
	"Water_Spout_Large",
	"Running_Man",
	"Fado",
	"Happy_Mask_Salesman",
	"Item_Model_Eyedrops",
	"Item_Model_Odd_Potion",
	"Item_Model_Odd_Mushroom",
	"Item_Model_Claim_Check",
	"Item_Model_Broken_Gorons_Sword_&_Giants_Knife",
	"Carpet_Merchant",
	"Graveyard_Boy",
	"Item_Model_Prescription",
	"Item_Model_Goron_Bracelet",
	"Item_Model_SOLD_OUT",
	"Item_Model_Eyeball_Frog",
	"Title_Logo",
	"Thieves_Hideout_Cell_Door",
	"Ganons_Tower_Exterior_Collapsing_Objects",
	"Death_Mountain_Eruption_Effects",
	"Adult_Zelda_Animations_I",
	"Adult_Zelda_Animations_II",
	"Item_Model_Goron_Mask",
	"Item_Model_Zora_Mask",
	"Item_Model_Gerudo_Mask",
	"Ganon",
	"Pierre_&_Bonooru",
	"Treasure_Chest_Shop_Proprietor",
	"Ganons_Tower_Door_Bars",
	"Item_Model_Hover_Boots",
	"Item_Model_Magic_Arrows",
	"Potion_Shop_Proprietor",
	"Ending_Cutscene_Animations",
	"Fishing_Pond_Objects",
	"Item_Model_Gold_Skulltula_Token",
	"Item_Model_Goddess_Spells",
	"Skulltula_House_Residents",
	"Big_Octo",
	"Bombchu_Bowling_Employee",
	"Sacred_Forest_Meadow_Objects",
	"Gerudos_Fortress_Objects",
	"Bombable_Boulder",
	"HintGiving_Deku_Scrub",
	"Bombchu_Shop_Proprietor",
	"Hyrule_Field_Objects_Adult",
	"Gerudo_in_Purple",
	"Business_Scrub",
	"Gerudo_Fighter_&_SecondinCommand",
	"CuccoChasing_Girl",
	"Dog",
	"Destructable_Iron_Knuckle_Objects",
	"Spirit_Temple_Door_&_Iron_Bars",
	"Empty",
	"Desert_Colossus_Objects",
	"Large_Wooden_Crate",
	"Forest_Stage_Judge",
	"Forest_Stage_Patron",
	"Item_Model_Blue_Fire",
	"Item_Model_Bug",
	"Item_Model_Butterfly",
	"Item_Model_Poe_Soul",
	"Item_Model_Fairys_Spirit",
	"Bombchu_Bowling_Alley_Barriers",
	"Inside_Ganons_Castle_Objects",
	"Death_Mountain_Cloud_Rings",
	"Item_Model_Bullet_Bags",
	"Ganondorf_Animations_I",
	"Ganondorf_Animations_II",
	"Ganondorf_Animations_III",
	"Item_Model_Rupees",
	"Kakariko_Village_Objects_Adult",
	"Kakariko_Village_Objects_Child",
	"Honey_&_Darling_Haggling_Townspeople",
	"Wolfos",
	"Stalchild",
	"Ganons_Lair_Destructable_Rubble",
	"Ganons_Lair_Destructable_Rubble_Fragment",
	"Shadow_Temple_Door_&_Shutter",
	"Gossip_Stone",
	"Poe_Collector",
	"Dodongos_Cavern_Bombable_Wall",
	"Cow",
	"Fat_Woman_in_Blue_&_Yellow_Vest",
	"Item_Model_Kokiri_Sword",
	"Door_Mimic",
	"Royal_Familys_Tomb_Door",
	"Time_Block",
	"Child_Zelda",
};

const char* gOoT_Actor[] = {
	"Link_Spawn_point",
	"Empty",
	"Stalfos",
	"Empty",
	"Shops",
	"Empty",
	"Empty",
	"Disintegrating_Blue_Flame",
	"Flame",
	"Wooden_Door",
	"Treasure_Chest",
	"Great_Fairy",
	"Proximity_Activated_Firewall",
	"Poe",
	"Octorok",
	"Webs",
	"Bomb",
	"Wallmaster",
	"Dodongo",
	"Keese",
	"Epona",
	"Collectable_Item",
	"Arrow",
	"Empty",
	"Fairy",
	"Cucco",
	"Empty",
	"Tektite",
	"Leever",
	"Peahat",
	"Butterfly",
	"Empty",
	"Bug",
	"Fish",
	"Empty",
	"Room_Changing_Black_Plane",
	"Unknown_scene_change",
	"Lizalfos",
	"Wooden_Post_with_Red_Cloth",
	"King_Dodongo",
	"Queen_Gohma",
	"Princess_Zelda_Child",
	"Cutscene_Actors",
	"Gohma_Larva",
	"Alpha_Cube_Copy",
	"Shabom",
	"Lifting_Wooden_Door",
	"Baby_Dodongo",
	"King_Dodongos_Fire",
	"Empty",
	"Boomerang",
	"Dark_Link",
	"Biri",
	"Taliparisan",
	"Empty",
	"Skulltula",
	"Torch_Slug",
	"Gameplay_keep_Objects",
	"Stinger",
	"Ambient_Sound_Effects",
	"Normal_Horse",
	"Shopkeeper",
	"Deku_Trees_Jaw",
	"Dodongo_Skulls_Jaw",
	"Lower_Part_of_Megaton_Statue",
	"Huge_Stone_Spike_Platform",
	"Ganondorfs_Horse",
	"Fire_Temple_Stone_Block",
	"Spinning_Flame_Thrower_Statue",
	"Stationary_Flame_Thrower_Statue",
	"Sink_Stone_Platform",
	"Fire_Temple_Stone_Block",
	"Sheik",
	"Flame_Circle",
	"Drawbridge",
	"Ground_Pounding_Moblin",
	"Bomb_Flower",
	"Adult_Zelda_Cutscene",
	"Elevator_Platform",
	"Lock_on_Blue_Spot",
	"Back_and_Forth_Moving_Platform",
	"Rotating_Spike_Cylinder",
	"Phantom_Ganon",
	"Empty",
	"Armos",
	"Deku_Baba",
	"Deku_Nuts_from_Link",
	"Spin_Attack",
	"Rising_Stone_Platform",
	"Dodongos_Cavern_Objects",
	"Lord_Jabu_Jabu",
	"Zeldas_Horse",
	"Stone_Stairs",
	"Blue_Warp",
	"Torch",
	"Heart_Container",
	"Deku_Scrub",
	"Large_Rotating_Stone_Ring",
	"Statue_Eyes",
	"Bari",
	"Dragon_Head_Statue",
	"Water_Temple_Water",
	"Hookshot",
	"Phantom_Ganons_Horse",
	"Twisted_Hallway",
	"Bubble",
	"Temple_of_Time_Windows",
	"Flying_Floor_Tile",
	"Master_Sword",
	"Phantom_Ganons_Lightning_Attack",
	"Warp_Pad",
	"Metal_Gate",
	"Door_of_Time",
	"Hammer_Steps_in_Fire_Temple",
	"Alpha_Bird",
	"Empty",
	"Empty",
	"Empty",
	"Empty",
	"Greenery",
	"Empty",
	"Empty",
	"Empty",
	"Empty",
	"Alpha_Large_Noisy_Stone",
	"Alpha_Stone_Cube",
	"Empty",
	"Empty",
	"Sliding_Spike_Trap",
	"Beta_Arrow_Trap",
	"Alpha_Orange_Pot",
	"Empty",
	"Talon",
	"Dampe_Grave_Digging_Game",
	"Lowering_Circular_Platform",
	"Forest_Temple_Elevator",
	"Forest_Temple_Rotating_Walls",
	"Forest_Temple_Ceiling",
	"Beamos",
	"Cutscene_Objects",
	"Cutscene_Environment_Effects_Objects",
	"Large_Firewall",
	"Floormaster",
	"Castle_Courtyard_Guards",
	"Redead_Gibdo",
	"Poe_Sisters",
	"Golden_Gauntlets_Rock",
	"Poe_Puzzle_Block",
	"Fish_Bugs_or_Butterflies",
	"Skullwalltula_Golden_Skulltula",
	"Flying_Volvagia",
	"Environmental_effects",
	"Darunia",
	"Fire_Dancer",
	"Child_Epona",
	"Hole_in_Ground_Exit",
	"Graveyard_Objects",
	"Gravestone",
	"Farores_Wind",
	"Dins_Fire",
	"Empty",
	"Young_Ruto",
	"Hole_Volvagia",
	"Flare_Dancer_Fire_Attack",
	"Deadhand",
	"Deadhands_Arms",
	"Rauru",
	"Enemy_Spawner",
	"Sage_Darunia_Cutscene",
	"Impa",
	"Treasure_Chest_Light",
	"Core_Fire_Dancer_Creature",
	"Volvagia_Platform",
	"Volvagia_Rocks",
	"Fake_Invisible_Objects",
	"Invisible_Objects_Metal_Gate",
	"Shadow_Temple_Ship",
	"Spinning_Scythe_Statues",
	"Empty",
	"Gate_Guards",
	"Falling_Rock_Spawner",
	"Flying_Rubble",
	"Flobbery_Muscle_Block",
	"Sun_Block_Switch_Hardcoded_Positions",
	"Gerudo_Valley_Objects",
	"Statue_from_Darunias_Room",
	"Barinade",
	"Open_Topped_Skull_Statue",
	"Shadow_temple_objects",
	"Coffin_Lid",
	"Bird_Statue_Bombables",
	"Crater_Smoke_Cone",
	"Shooting_Gallery_Game",
	"Shooting_Gallery_Man",
	"Shop_Shelves",
	"Nabooru",
	"Morpha",
	"Shell_Blade",
	"Big_Octorok",
	"Withered_Deku_Baba",
	"Jabu_Jabu_Objects",
	"Sage_Saria_Cutscene",
	"Gorons_Cutscene",
	"Ingo",
	"Koume_and_Kotake",
	"Giant_Boulder_Blocking_Dodongos_Cavern",
	"Empty",
	"Cracked_Stone_Platform",
	"2D_Bombable_Wall",
	"Ice_Platform",
	"Adult_Ruto",
	"Deku_Tree_Sprout",
	"Water_Noise",
	"Lake_Hylia_Objects",
	"Moveable_Ice_Block",
	"Bottom_of_the_well_water_level_changer",
	"Empty",
	"Adult_Malon",
	"Bombchu",
	"Horseback_Games",
	"Twinrova",
	"Like_Like",
	"Tentacle_from_Inside_Lord_Jabu_Jabu",
	"Blocking_Tentacle_from_Jabu_Jabu",
	"Anubis_Body",
	"Anubis_Fire_Attack",
	"Ladder_with_Clasp_Unused",
	"Gates_and_Rotating_Pillars",
	"Forest_Temple_Well_Water",
	"Death_Mountain_Cloud_Ring",
	"Switch_from_Inside_Lord_Jabu_Jabu",
	"Young_Malon",
	"Boss_Ganondorf",
	"Bongo_Bongo",
	"Empty",
	"Empty",
	"Spike_Enemy",
	"Frogs_and_Ocarina_Spot",
	"Deku_Shield",
	"Large_Red_Ice",
	"Blue_Flame",
	"Ocarina_of_Time",
	"Empty",
	"Empty",
	"Nayrus_Love",
	"Cutscene_Effects",
	"Anubis",
	"Shadow_Temple_Truth_Spinner",
	"Hyrule_Castle_Gate",
	"Giant_Rolling_Boulder",
	"Moving_Brick_Wall",
	"Empty",
	"Rotating_Cobra_Mirror",
	"Climbable_Mesh_Wall",
	"Fishing_Game_Fish_and_Fisherman",
	"Push_Block",
	"Death_Mountain_Trail_Gate",
	"Dust_Motes_Gathering_Together",
	"Windmill_Sails",
	"Kakariko_Village_Well_Crossbeams",
	"Kakariko_Well_Water",
	"Golden_Torch_Stand_Poe_Sisters",
	"Floor_of_Ganondorfs_Room",
	"Milk_Crate",
	"Lon_Lon_Ranch_Horse_Jumping_Fence",
	"Empty",
	"Fire_Arrow",
	"Ice_Arrow",
	"Light_Arrow",
	"Empty",
	"Empty",
	"GI_Collectables_Shields_Bottles_etc",
	"Small_Wooden_Crate",
	"Breakable_Pot",
	"Invisible_Collectibles",
	"Iron_Knuckle",
	"Iron_Knuckle_Armor_Pieces",
	"Skullkid",
	"Skullkids_Needle",
	"Silver_Rupee_Large_Rotating_Pot",
	"Vortex_Koume_Kotake_kidnap_Nabooru",
	"Bongo_Bongo_Shadow",
	"Business_Scrub",
	"Navi_Information_Spot",
	"Eye_Switch_and_Flame_that_Follows_Link",
	"Flying_Magic_Pot",
	"Ice_That_Covers_Switches",
	"Zoras_River_Waterfall",
	"Zoras_Domain_Waterfall",
	"Freezard",
	"Dampes_Ghost",
	"Rotating_Windmill_Mechanism",
	"Zora_Diving_Game",
	"Grass_Clump_doesnt_regrow",
	"Bean_Planting_Spot",
	"Bombable_Rock",
	"Empty",
	"Empty",
	"Dungeon_Switches",
	"Huge_Stone_Switch_Stone_Elevator",
	"Square_Collapsing_Platform",
	"Stone_Hookshot_Target",
	"Play_Ocarina_Here_Spot",
	"Horseback_Archery_Target",
	"Rolling_Boulder",
	"Sparkling_Rupee",
	"Head_Carpenter",
	"Carpenters",
	"Empty",
	"Alpha_Blue_Balls",
	"Dark_Links_Illusion_Room",
	"Item_Inbox",
	"White_Clothed_Gerudo",
	"Block_Save_Point",
	"Alpha_Link_Shadow_Activator",
	"Alpha_Arwing",
	"Cucco_Lady",
	"Medigoron",
	"Bean_Seller",
	"Carpenters_Son",
	"Ingos_Gates",
	"Square_Signpost",
	"Hyrule_Castle_Guard",
	"Hopping_Cucco_Not_Solid",
	"Attacking_Cucco",
	"Stone_Blocking_Well_Entrance",
	"Saria",
	"Checkable_Spot",
	"Rainbow_Bridge",
	"Potion_Shop_Lady",
	"Lake_Hylia_Doctor",
	"Bombchu_Bowling_Girl",
	"Bombchu_Bowling_Pit",
	"Kaepora_Gaebora",
	"Rock",
	"Grave_Flower",
	"Light_Activated_Sun_Switch_Sun_Block",
	"Circle_of_Bushes",
	"Unused_Gorons",
	"Windmill_Man",
	"Empty",
	"Treasure_Chests_from_Treasure_Box_Game",
	"Large_Stone_Face_Spirit_Temple",
	"Hanging_Platform_Spirit_Temple",
	"Large_Circular_Mirror_Spirit_Temple",
	"Light_Blocking_Rock_Spirit_Temple",
	"Circular_Lifting_Metal_Shutter_Spirit_Temple",
	"Bombable_Rock_Wall_Spirit_Temple",
	"Giant_Three_Sided_Goron_Statue",
	"Empty",
	"Ganondorfs_Organ",
	"Water_Spout",
	"Whirlpool_Effect",
	"Empty",
	"Running_Man",
	"Kokiri",
	"King_Zora",
	"Weather_Effects",
	"Bongo_Bongo_Floor",
	"Kakariko_Village_Rooftop_Man",
	"Mini_Game_Displayed_GI_Models",
	"Brick_Pillar_Spirit_Temple",
	"Bombchu_Salesman",
	"Flying_Carpet",
	"Graveyard_Boy",
	"Mido",
	"Hylians",
	"Ganondorfs_Mantle",
	"Rain_and_Lightning",
	"Title_Screen_Actor",
	"Fortress_Metal_Grate_Door",
	"Targetable_Navi_Spot",
	"Ganons_Tower_Collapsing",
	"Hyrule_Field_Poes_Big_Poes",
	"Lava_Sprites",
	"Metal_Bars",
	"Hyrule_Guard",
	"Adult_Zelda",
	"Ganon",
	"Scarecrow",
	"Treasure_Chest_Shop_Man",
	"Push_Block_Hardcoded_Positions",
	"Suns_Song_effect",
	"The_End_Message",
	"Empty",
	"Treasure_Chest_Variable_chosen_by_Hole",
	"Ranch_NPCs_Ending_Cutscene",
	"Fire_Arrow_Shot_Suns_Song_Fairy",
	"Great_Fairys_Pink_and_Yellow_Beams",
	"Checkable_Spot",
	"Patrolling_Gerudo",
	"Room_Timer",
	"Cursed_Skulltula_People",
	"Uncursed_Skulltula_People",
	"Zeldas_Lullaby_Effect",
	"Song_of_Storms_Effect",
	"Stingray",
	"Sacred_Forest_Meadow_Water_and_Gate",
	"Stone_Platform",
	"Pillar_after_being_hit_by_Iron_Knuckle",
	"Gerudo_Fortress_wooden_gate",
	"Gerudo_Training_Area_Gate",
	"Green_Deku_Scrubs",
	"Deku_Scrubs_Attack",
	"Broken_Drawbridge",
	"Grounded_Business_Scrub",
	"Dampe_Game_Collectables",
	"Gerudo_Fighter",
	"Eponas_Song_Effect",
	"Sarias_Song_Effect",
	"Child_Chasing_Cucco_in_Hyrule_Market",
	"Dog",
	"Golden_Skulltula_Token",
	"Semi_Built_Shooting_Gallery",
	"Beehive",
	"Desert_Colossus_Bombable_Wall",
	"Crate",
	"Deku_Stage_Cutscene",
	"Deku_Stage_Judge",
	"Deku_Panel",
	"Man_in_Purple_Pants_and_White_Top",
	"Bombchu_Bowling_Alley_Game",
	"Carpenters_Son_Child",
	"Ganons_Tower_Magic_Barrier",
	"Zoras_Fountain_Bombable_Wall",
	"Death_Mountain_Crater_Bombable_Wall",
	"Empty",
	"Tower_of_Rupees",
	"Honey_and_Darling",
	"Haggling_Townspeople",
	"Gorons_and_Biggoron",
	"Wolfos",
	"Stalchildren",
	"Ganon_Battle_Rubble",
	"Crumbling_Stone",
	"Sinkable_Lava_Platform",
	"Invisible_Transparent_Platforms",
	"Web_Blocked_Light_Window",
	"2D_Stone_Wall",
	"Large_Ice_Cube",
	"Poe_Collector",
	"Gossip_Stone",
	"Water_Temple_Bombable_Walls",
	"Metal_Gate",
	"Carpenters_in_Kakariko",
	"Bombchu_Bowling_Alley_Wall",
	"Bombchu_Bowling_Bullseyes_Pits_used_by_game_engine",
	"Haunted_Wasteland_Guiding_Poe",
	"Guay",
	"Fake_Stomping_Door",
	"Refilling_Oasis",
	"Lid_to_the_Giant_Goron_Pot",
	"Goron_Room_Door",
	"Adult_Malon_Ranch",
	"Cow",
	"Ice_Stalagmite_Stalagtite",
	"2D_Ice_Bars",
	"Scarecrow_Song_Spot",
	"Bonooru_the_Scarecrow",
	"Song_of_Time_Effect",
	"Void_Trigger",
	"Circular_Piece_of_Stone_Wall",
	"Zora",
	"Skulltula_Sprouting_from_Bean_Spot",
	"Gerudo_giving_you_Membership_Card",
	"Time_Block",
	"Bronze_Boulder",
	"Princess_Zelda_Child",
	"Running_Man_Adult",
	"Young_Link_Silver_Block",
	"Exchangeable_Time_Block",
};

const char* gOoT_Effect[] = {
	"Dust",
	"Sparkle",
	"Bomb_Unused",
	"Bomb_Blast",
	"Shockwave",
	"Spark",
	"Fire_Dodongo",
	"Bubble_1",
	"Empty",
	"Ripple",
	"Splash",
	"Magma_1",
	"Flame_Footprint",
	"Lightning",
	"Bubble_2",
	"Fragment_1",
	"Broken_Weapon",
	"Bubble_Gohma",
	"Bubble_Unused",
	"Magma_2",
	"Stone",
	"HitMark",
	"Shock_Light_Ball",
	"Fire_1",
	"Vision_Sphere",
	"Fragment_2",
	"Ice_Shard",
	"Ice_Clumps",
	"Fire_2",
	"Fire_3",
	"Score",
	"Fire_Circle",
	"Death_Flame",
	"Effect_Dead_Dd",
	"Effect_Dead_Ds",
	"Death_Sfx_Only",
	"Ice_Smoke",
};

const char* gOoT_State[] = {
	"Title_Setup",
	"Level_Select",
	"Boot_Title",
	"Game_play",
	"Opening",
	"File_Choose"
};

const char* gOoT_Kaleido[] = {
	"Pause",
	"Player",
};

const char* gOoT_Scene[] = {
	"Inside_the_Deku_Tree",
	"Dodongos_Cavern",
	"Inside_Jabu_Jabus_Belly",
	"Forest_Temple",
	"Fire_Temple",
	"Water_Temple",
	"Spirit_Temple",
	"Shadow_Temple",
	"Bottom_of_the_Well",
	"Ice_Cavern",
	"Ganons_Tower",
	"Gerudo_Training_Ground",
	"Thieves_Hideout",
	"Inside_Ganons_Castle",
	"Ganons_Tower_Collapsing",
	"Inside_Ganons_Castle_Collapsing",
	"Treasure_Box_Shop",
	"Gohmas_Lair",
	"King_Dodongos_Lair",
	"Barinades_Lair",
	"Phantom_Ganons_Lair",
	"Volvagias_Lair",
	"Morphas_Lair",
	"Twinrovas_Lair",
	"Bongo_Bongos_Lair",
	"Ganondorfs_Lair",
	"Ganons_Tower_Exterior_Collapsing",
	"Market_Entrance_Child_Day",
	"Market_Entrance_Child_Night",
	"Market_Entrance_Ruins",
	"Back_Alley_Child_Day",
	"Back_Alley_Child_Night",
	"Market_Child_Day",
	"Market_Child_Night",
	"Market_Ruins",
	"Temple_of_Time_Exterior_Child_Day",
	"Temple_of_Time_Exterior_Child_Night",
	"Temple_of_Time_Exterior_Ruins",
	"Know_It_All_Brothers_House",
	"House_of_Twins",
	"Midos_House",
	"Sarias_House",
	"Kakariko_Tenement",
	"Back_Alley_House_Man_in_Green",
	"Bazaar",
	"Kokiri_Shop",
	"Goron_Shop",
	"Zora_Shop",
	"Kakariko_Potion_Shop",
	"Market_Potion_Shop",
	"Bombchu_Shop",
	"Happy_Mask_Shop",
	"Links_House",
	"Back_Alley_House_Dog_Lady",
	"Stable",
	"Impas_House_Cucco_Ladys_home",
	"Lakeside_Laboratory",
	"Carpenters_Tent",
	"Gravekeepers_Hut",
	"Great_Fairys_Fountain_Upgrades",
	"Fairys_Fountain",
	"Great_Fairys_Fountain_Spells",
	"Grottos",
	"Grave_Redead",
	"Grave_Fairys_Fountain",
	"Royal_Familys_Tomb",
	"Shooting_Gallery",
	"Temple_of_Time",
	"Chamber_of_the_Sages",
	"Castle_Hedge_Maze_Day",
	"Castle_Hedge_Maze_Night",
	"Cutscene_Map",
	"Dampes_Grave_&_Windmill",
	"Fishing_Pond",
	"Castle_Courtyard",
	"Bombchu_Bowling_Alley",
	"Ranch_House_&_Silo",
	"Guard_House",
	"Grannys_Potion_Shop",
	"Ganons_Tower_Collapse_&_Battle_Arena",
	"House_of_Skulltula",
	"Hyrule_Field",
	"Kakariko_Village",
	"Graveyard",
	"Zoras_River",
	"Kokiri_Forest",
	"Sacred_Forest_Meadow",
	"Lake_Hylia",
	"Zoras_Domain",
	"Zoras_Fountain",
	"Gerudo_Valley",
	"Lost_Woods",
	"Desert_Colossus",
	"Gerudos_Fortress",
	"Haunted_Wasteland",
	"Hyrule_Castle",
	"Death_Mountain_Trail",
	"Death_Mountain_Crater",
	"Goron_City",
	"Lon_Lon_Ranch",
	"Ganons_Castle_Exterior",
	"Jungle_Gym",
	"Ganondorf_Test_Room",
	"Depth_Test",
	"Stalfos_MiniBoss_Room",
	"Stalfos_Boss_Room",
	"Sutaru",
	"Castle_Hedge_Maze_Early",
	"Sasa_Test",
	"Treasure_Chest_Room",
};

const char* gOoT_Soundfont[] = {
	"Master_Bank",
	"Actor",
	"Nature",
	"Main_Orchestra",
	"Deku_Tree",
	"Hylian_Troupe",
	"Title_Screen",
	"Jabu_Jabu",
	"Kakariko_Guitar",
	"Harp_String",
	"Fire_Temple",
	"Dodongos_Cavern",
	"Forest_Temple",
	"Lon_Lon_Ranch",
	"Goron_City",
	"Kokiri_Forest",
	"Spirit_Temple",
	"Race",
	"Warp_Song",
	"Legend_of_Hyrule",
	"Minigame_Shop",
	"Zoras_Domain",
	"Shop",
	"Ice_Cavern",
	"Shadow_Temple",
	"Water_Temple",
	"Unused_Piano",
	"Gerudo_Valley",
	"Potion_Shop",
	"Kotake_Koume",
	"Organ",
	"Inside_Ganons_Castle",
	"Battle",
	"Ending_A",
	"Ending_B",
	"Fanfare",
	"Kaepora_Gaebora",
	"Unk",
	"Unk",
	"Unk",
	"Unk",
};

const char* gOoT_Sequence[] = {
	"Master_Sequence",
	"Nature_Ambience",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Hyrule_Field",
	"Dodongos_Cavern",
	"Kakariko_Village_(Adult)",
	"Battle",
	"Boss_Battle",
	"Inside_the_Deku_Tree",
	"Market",
	"Title_Theme",
	"House",
	"Game_Over",
	"Boss_Clear",
	"Obtain_Item",
	"Enter_Ganondorf",
	"Obtain_Heart_Container",
	"Prelude_of_Light",
	"Inside_Jabu_Jabus_Belly",
	"Kakariko_Village_(Child)",
	"Great_Fairys_Fountain",
	"Zeldas_Theme",
	"Fire_Temple",
	"Open_Treasure_Chest",
	"Forest_Temple",
	"Hyrule_Castle_Courtyard",
	"Ganondorfs_Theme",
	"Lon_Lon_Ranch",
	"Goron_City",
	"Hyrule_Field_Morning_Theme",
	"Spiritual_Stone_Get",
	"Bolero_of_Fire",
	"Minuet_of_Woods",
	"Serenade_of_Water",
	"Requiem_of_Spirit",
	"Nocturne_of_Shadow",
	"Mini_Boss_Battle",
	"Obtain_Small_Item",
	"Temple_of_Time",
	"Lon_Lon_Ranch",
	"Kokiri_Forest",
	"Obtain_Fairy_Ocarina",
	"Lost_Woods",
	"Spirit_Temple",
	"Horse_Race",
	"Horse_Race_Goal",
	"Ingos_Theme",
	"Obtain_Medallion",
	"Sarias_Song",
	"Eponas_Song",
	"Zeldas_Lullaby",
	"Suns_Song",
	"Song_of_Time",
	"Song_of_Storms",
	"Fairy_Flying",
	"Deku_Tree",
	"Windmill_Hut",
	"Legend_of_Hyrule",
	"Shooting_Gallery",
	"Sheiks_Theme",
	"Zoras_Domain",
	"Enter_Zelda",
	"Goodbye_to_Zelda",
	"Master_Sword",
	"Intro_Ganon",
	"Shop",
	"Chamber_of_theSages",
	"File_Select",
	"Ice_Cavern",
	"Open_Door_of_Temple_of_Time",
	"Kaepora_Gaeboras_Theme",
	"Shadow_Temple",
	"Water_Temple",
	"Ganons_Castle_Bridge",
	"Ocarina_of_Time",
	"Gerudo_Valley",
	"Potion_Shop",
	"Kotake_Koumes_Theme",
	"Escape_from_Ganons_Castle",
	"Ganons_Castle_Underground",
	"Ganondorf_Battle",
	"Ganon_Battle",
	"Seal_of_Six_Sages",
	"End_Credits_I",
	"End_Credits_II",
	"End_Credits_III",
	"End_Credits_IV",
	"Volvagia_Boss_Battle",
	"Mini_Game",
	"Nothing",
	"Nothing",
	"Nothing",
	"Nothing",
	"Nothing",
};

const SystemInfo gOoT_Static[26] = {
	{ 6,    "link_animation"              },
	{ 7,    "icon_item_static"            },
	{ 8,    "icon_item_24_static"         },
	{ 9,    "icon_item_field_static"      },
	{ 10,   "icon_item_dungeon_static"    },
	{ 11,   "icon_item_gameover_static"   },
	{ 12,   "icon_item_NES_static"        },
	{ 15,   "item_name_static"            },
	{ 16,   "map_name_static"             },
	{ 17,   "do_action_static"            },
	{ 18,   "message_static"              },
	{ 19,   "message_texture_static"      },
	{ 20,   "nes_font_static"             },
	{ 21,   "message_data_static_NES"     },
	{ 24,   "message_data_static_staff"   },
	{ 25,   "map_grand_static"            },
	{ 26,   "map_i_static"                },
	{ 27,   "map_48x85_static"            },
	{ 937,  "z_select_static"             },
	{ 938,  "nintendo_rogo_static"        },
	{ 939,  "title_static"                },
	{ 940,  "parameter_static"            },
	{ 1005, "elf_message_field"           },
	{ 1006, "elf_message_ydan"            },
	
	{ 1,    "z_boot"                      },
	{ 28,   "z_code"                      },
};

const char* gOoT_Skybox[] = {
	"Skybox_Clear_Sunrise",
	"Skybox_Clear_Day",
	"Skybox_Clear_Sunset",
	"Skybox_Clear_Night",
	"Skybox_Overcast_Sunrise",
	"Skybox_Overcast_Day",
	"Skybox_Overcast_Sunset",
	"Skybox_Overcast_Night",
	"Skybox_Demo1",
	"Skybox_Demo2",
	"Prerender_Market_Child_Day",
	"Prerender_Market_Child_Night",
	"Prerender_Market_Ruins",
	"Prerender_Links_House",
	"Prerender_Know-It-All_Brothers_House",
	"Prerender_House_of_Twins",
	"Prerender_Midos_House",
	"Prerender_Sarias_House",
	"Prerender_Bazaar",
	"Prerender_Stable",
	"Prerender_Carpenter_Bosss_House",
	"Prerender_Back_Alley_House_Man_in_Green",
	"Prerender_Back_Alley_House_Dog_Lady",
	"Prerender_Shop_Kokiri",
	"Prerender_Shop_Goron",
	"Prerender_Shop_Zora",
	"Prerender_Shop_Kakariko",
	"Prerender_Shop_Market",
	"Prerender_Bombchu_Shop",
	"Prerender_Impas_House",
	"Prerender_Carpenters_Tent",
	"Prerender_Happy_Mask_Shop",
};

const char* gOoT_PlayerAnim[] = {
	/* 0 */ "ChestOpen_JumpInside",
	/* 1 */ "ChestOpen_JumpInsideAndOut",
	/* 2 */ "Cs_ShockedFall",
	/* 3 */ "Cs_Darunia_HeadPatKnock",
	/* 4 */ "Child_OpenDoor",
	/* 5 */ "Child_OpenDoor2",
	/* 6 */ "Cs_FallSitting",
	/* 7 */ "OpenArms",
	/* 8 */ "OpenArmsRise",
	/* 9 */ "OpenArmsLower",
	/* 10 */ "Cs_PullMasterSword",
	/* 11 */ "Cs_Take2StepsBackwards",
	/* 12 */ "Cs_EquipSword",
	/* 13 */ "Cs_StandWieldingSword",
	/* 14 */ "Cs_LookAround_A",
	/* 15 */ "Cs_LookAround_B",
	/* 16 */ "Cs_GetUpStandingWatchLeft",
	/* 17 */ "Cs_StandWatchLeft",
	/* 18 */ "Cs_LookThroughWindow",
	/* 19 */ "Cs_HopOffPedestal",
	/* 20 */ "Cs_GetUpCleanUpTunic",
	/* 21 */ "Cs_SitOnGround",
	/* 22 */ "Ladder_BotEnd",
	/* 23 */ "Ladder_BotEnd2",
	/* 24 */ "Ladder_TopEnd",
	/* 25 */ "Ladder_TopEnd2",
	/* 26 */ "Ladder_GetOnFromBot",
	/* 27 */ "Ladder_GetOnFromTop",
	/* 28 */ "Ladder_Climb_A",
	/* 29 */ "Ladder_Climb_B",
	/* 30 */ "Unk_30",
	/* 31 */ "Cs_Bed_TurnHead",
	/* 32 */ "Cs_Bed_WakeUp",
	/* 33 */ "Cs_Bed_NodAndGetOff",
	/* 34 */ "Cs_Bed_Idle",
	/* 35 */ "Cs_Bed_IdleHeadTurned",
	/* 36 */ "Cs_Bed_Sit",
	/* 37 */ "Unk_37",
	/* 38 */ "Cs_LookAroundUp_A",
	/* 39 */ "Cs_LookAroundUp_B",
	/* 40 */ "Cs_Zelda_Idle",
	/* 41 */ "Cs_Zelda_TakeHandOffOcarina",
	/* 42 */ "Cs_Zelda_HandOverOcarina",
	/* 43 */ "Cs_Zelda_HandOnOcarinaIdle",
	/* 44 */ "Cs_SurpriseLeftRight",
	/* 45 */ "Combat_2H_Unk_48",
	/* 46 */ "Combat_2H_Unk_49",
	/* 47 */ "Combat_2H_Unk_50",
	/* 48 */ "Combat_2H_Unk_51",
	/* 49 */ "Combat_2H_Unk_52",
	/* 50 */ "Combat_2H_Unk_53",
	/* 51 */ "Combat_2H_Unk_54",
	/* 52 */ "Combat_2H_Unk_55",
	/* 53 */ "Combat_2H_Unk_56",
	/* 54 */ "Combat_1H_Unk_57",
	/* 55 */ "Combat_1H_Unk_58",
	/* 56 */ "Combat_1H_Unk_59",
	/* 57 */ "Combat_1H_Unk_60",
	/* 58 */ "Combat_1H_PullSwordAggressive",
	/* 59 */ "Combat_1H_BackwalkBrake",
	/* 60 */ "Combat_1H_HurtBack",
	/* 61 */ "Combat_1H_Backwalk",
	/* 62 */ "Combat_Bomb_SideWalkLeft",
	/* 63 */ "Combat_Bomb_SideWalkRight",
	/* 64 */ "Defence_1H_Block",
	/* 65 */ "Defence_2H_Block",
	/* 66 */ "Defence_2H_Block2",
	/* 67 */ "Combat_1H_HurtFront",
	/* 68 */ "Combat_1H_Unused_71",
	/* 69 */ "Combat_1H_FallLand",
	/* 70 */ "Combat_1H_Attack_Unk_73",
	/* 71 */ "Combat_1H_Attack_Unk_74",
	/* 72 */ "Combat_1H_Attack_Unk_75",
	/* 73 */ "Combat_1H_Attack_Unk_76",
	/* 74 */ "Combat_1H_Attack_Unk_77",
	/* 75 */ "Combat_1H_SideWalkLeft",
	/* 76 */ "Combat_1H_SideWalkRight",
	/* 77 */ "Unused_Shield_80",
	/* 78 */ "Defence_1H_Shield",
	/* 79 */ "Defence_2H_Shield",
	/* 80 */ "Combat_1H_StandL",
	/* 81 */ "Unused_81",
	/* 82 */ "Unused_82",
	/* 83 */ "Unused_83",
	/* 84 */ "Unused_84",
	/* 85 */ "Unused_85",
	/* 86 */ "Defence_1H_ShieldPoseR",
	/* 87 */ "Defence_2H_ShieldPoseR",
	/* 88 */ "Combat_1H_StandR",
	/* 89 */ "Defence_1H_ShieldCrouch_A",
	/* 90 */ "Defence_1H_ShieldCrouch_B",
	/* 91 */ "Unused_Combat_1H_JumpR",
	/* 92 */ "Unused_Defence_1H_CrouchStab",
	/* 93 */ "Boomerang_Catch",
	/* 94 */ "Boomerang_Throw",
	/* 95 */ "Boomerang_Throw2",
	/* 96 */ "Boomerang_Throw3",
	/* 97 */ "Boomerang_StandbyWalkL",
	/* 98 */ "Boomerang_StandbyWalkR",
	/* 99 */ "Boomerang_TakeStance",
	/* 100 */ "Boomerang_StandbyL",
	/* 101 */ "Boomerang_StandbyR",
	/* 102 */ "Bottle_CloseAndHoldUp",
	/* 103 */ "Bottle_Swing",
	/* 104 */ "Bottle_ReleaseFairy",
	/* 105 */ "Bottle_Drink",
	/* 106 */ "Bottle_Drink_C",
	/* 107 */ "Bottle_Drink_A",
	/* 108 */ "Bottle_Drink_B",
	/* 109 */ "Bottle_CloseAndHoldUp2",
	/* 110 */ "Bottle_SwingLow",
	/* 111 */ "Bottle_Release",
	/* 112 */ "Bottle_ReleaseOnHand",
	/* 113 */ "Bottle_PutBackToBottle",
	/* 114 */ "Bow_TakeAim",
	/* 115 */ "Bow_Shoot",
	/* 116 */ "Bow_PutDown",
	/* 117 */ "Bow_Reload",
	/* 118 */ "Bow_AimIdle",
	/* 119 */ "Defence_Bow_Shield_A",
	/* 120 */ "Defence_Bow_Shield_B",
	/* 121 */ "Bow_StandbyWalkL",
	/* 122 */ "Bow_StandbyWalkR",
	/* 123 */ "Bow_StandbyWalkSlowR",
	/* 124 */ "Bow_StandbySettleLegs",
	/* 125 */ "Tunnel_Crawl",
	/* 126 */ "Tunnel_Crawl_C",
	/* 127 */ "Tunnel_Crawl_A",
	/* 128 */ "Unused_FallIntoChest",
	/* 129 */ "Chest_Adult_OpenAndPickUp",
	/* 130 */ "MasterSword_PutBackOnPedestal",
	/* 131 */ "Cs_ShockEarthquake_A",
	/* 132 */ "Cs_ShockEarthquake_B",
	/* 133 */ "Cs_ShockEarthquake_C",
	/* 134 */ "Cs_Shocked2",
	/* 135 */ "Door_WhileHolding_OpenR",
	/* 136 */ "Door_OpenR",
	/* 137 */ "Door_WhileHolding_OpenL",
	/* 138 */ "Door_OpenL",
	/* 139 */ "Cs_TurnAround",
	/* 140 */ "Cs_StandTurnedAround",
	/* 141 */ "Cs_ShockTurnAround",
	/* 142 */ "Chest_TurnAndHoldItem",
	/* 143 */ "Chest_HoldItem",
	/* 144 */ "Door_ShockShutterLock",
	/* 145 */ "Cs_Ganondorf_MagicBlock_A",
	/* 146 */ "Cs_Ganondorf_MagicBlock_B",
	/* 147 */ "Cs_Ganondorf_LinkChecksHimself",
	/* 148 */ "Cs_Zelda_RunAgainstCrystal",
	/* 149 */ "Cs_Zelda_LookAtCrystalAndHit",
	/* 150 */ "Cs_Zelda_LookUpCrystalRising_A",
	/* 151 */ "Cs_Zelda_LookUpCrystalRising_B",
	/* 152 */ "Cs_Zelda_LookAtZeldaInCrystal",
	/* 153 */ "Cs_Zelda_StunFlash_B",
	/* 154 */ "Cs_Zelda_StunFlash_A",
	/* 155 */ "Cs_Ganon_ShiningMasterSword_A",
	/* 156 */ "Cs_Ganon_ShiningMasterSword_B",
	/* 157 */ "Cs_Ganon_ShiningMasterSword_C",
	/* 158 */ "Cs_Ganon_ShiningMasterSword_E",
	/* 159 */ "Cs_Ganon_ShiningMasterSword_D",
	/* 160 */ "Gerudo_HandsUp",
	/* 161 */ "Cs_Ganondorf_LookAtHandTriforce_A",
	/* 162 */ "Cs_Ganondorf_LookAtHandTriforce_B",
	/* 163 */ "Cs_GanondorfCastle_LookDownPit_A",
	/* 164 */ "Cs_GanondorfCastle_LookDownPit_B",
	/* 165 */ "MasterSword_PulledFromPedestalSwing",
	/* 166 */ "MasterSword_PullUp",
	/* 167 */ "Unk_167_A",
	/* 168 */ "Unk_168_B",
	/* 169 */ "Unk_169_C",
	/* 170 */ "BlueWarp",
	/* 171 */ "Unk_171_A",
	/* 172 */ "Unk_172_B",
	/* 173 */ "DieAndRevive",
	/* 174 */ "Combat_2H_Unk_174",
	/* 175 */ "Combat_2H_Unk_175",
	/* 176 */ "Combat_2H_Unk_176",
	/* 177 */ "Combat_2H_Unk_177",
	/* 178 */ "Combat_2H_Unk_178",
	/* 179 */ "Combat_2H_Unk_179",
	/* 180 */ "Combat_2H_Unk_180",
	/* 181 */ "Combat_2H_Unk_181",
	/* 182 */ "Combat_2H_Unk_182",
	/* 183 */ "Combat_2H_Unk_183",
	/* 184 */ "Combat_2H_Unk_184",
	/* 185 */ "Combat_2H_Unk_185",
	/* 186 */ "Combat_2H_Unk_186",
	/* 187 */ "Combat_2H_Unk_187",
	/* 188 */ "Combat_2H_Unk_188",
	/* 189 */ "Combat_2H_Unk_189",
	/* 190 */ "Combat_2H_Jumpslash_A",
	/* 191 */ "Combat_2H_Jumpslash_C",
	/* 192 */ "Combat_2H_Jumpslash_B",
	/* 193 */ "Combat_2H_Spin_WalkSide",
	/* 194 */ "Combat_2H_Spin_TakeStance",
	/* 195 */ "Combat_2H_Spin_Standby",
	/* 196 */ "Combat_2H_Spin_Cancel",
	/* 197 */ "Combat_2H_Spin_WalkForward",
	/* 198 */ "Combat_2H_Spin_Spin",
	/* 199 */ "Combat_2H_Spin_SpinEnd",
	/* 200 */ "SideHopL",
	/* 201 */ "Combat_1H_SideHopL_Land",
	/* 202 */ "SideHopL_Land_1H",
	/* 203 */ "Combat_1H_Unk_203",
	/* 204 */ "Combat_1H_Unk_204",
	/* 205 */ "Combat_1H_Unk_205",
	/* 206 */ "Combat_1H_Unk_206",
	/* 207 */ "SideHopR",
	/* 208 */ "Combat_1H_SideHopR_Land",
	/* 209 */ "SideHopR_Land_1H",
	/* 210 */ "Combat_1H_Unk_210",
	/* 211 */ "Combat_1H_Unk_211",
	/* 212 */ "Combat_1H_Unk_212",
	/* 213 */ "Combat_1H_Unk_213",
	/* 214 */ "Combat_1H_QuickSpin_Spin",
	/* 215 */ "Combat_1H_QuickSpin_SpinEnd",
	/* 216 */ "BackFlip",
	/* 217 */ "Combat_1H_BackFlipR_Land",
	/* 218 */ "BackFlip_Land_1H",
	/* 219 */ "Run_Damage1",
	/* 220 */ "Run_Damage2",
	/* 221 */ NULL,
	/* 222 */ NULL,
	/* 223 */ NULL,
	/* 224 */ NULL,
	/* 225 */ NULL,
	/* 226 */ NULL,
	/* 227 */ NULL,
	/* 228 */ NULL,
	/* 229 */ NULL,
	/* 230 */ NULL,
	/* 231 */ NULL,
	/* 232 */ NULL,
	/* 233 */ NULL,
	/* 234 */ NULL,
	/* 235 */ NULL,
	/* 236 */ NULL,
	/* 237 */ NULL,
	/* 238 */ NULL,
	/* 239 */ NULL,
	/* 240 */ NULL,
	/* 241 */ NULL,
	/* 242 */ NULL,
	/* 243 */ NULL,
	/* 244 */ NULL,
	/* 245 */ NULL,
	/* 246 */ NULL,
	/* 247 */ NULL,
	/* 248 */ NULL,
	/* 249 */ NULL,
	/* 250 */ NULL,
	/* 251 */ NULL,
	/* 252 */ NULL,
	/* 253 */ NULL,
	/* 254 */ NULL,
	/* 255 */ NULL,
	/* 256 */ NULL,
	/* 257 */ NULL,
	/* 258 */ NULL,
	/* 259 */ NULL,
	/* 260 */ NULL,
	/* 261 */ "Run_1H",
	/* 262 */ "Run_2H",
	/* 263 */ NULL,
	/* 264 */ NULL,
	/* 265 */ NULL,
	/* 266 */ NULL,
	/* 267 */ NULL,
	/* 268 */ NULL,
	/* 269 */ NULL,
	/* 270 */ NULL,
	/* 271 */ NULL,
	/* 272 */ NULL,
	/* 273 */ NULL,
	/* 274 */ NULL,
	/* 275 */ NULL,
	/* 276 */ NULL,
	/* 277 */ NULL,
	/* 278 */ NULL,
	/* 279 */ NULL,
	/* 280 */ NULL,
	/* 281 */ NULL,
	/* 282 */ "Stand_2H",
	/* 283 */ NULL,
	/* 284 */ NULL,
	/* 285 */ "Walk_2H",
	/* 286 */ NULL,
	/* 287 */ NULL,
	/* 288 */ NULL,
	/* 289 */ NULL,
	/* 290 */ NULL,
	/* 291 */ NULL,
	/* 292 */ NULL,
	/* 293 */ NULL,
	/* 294 */ NULL,
	/* 295 */ NULL,
	/* 296 */ NULL,
	/* 297 */ NULL,
	/* 298 */ NULL,
	/* 299 */ NULL,
	/* 300 */ NULL,
	/* 301 */ NULL,
	/* 302 */ NULL,
	/* 303 */ NULL,
	/* 304 */ "Hookshot_Pull_A",
	/* 305 */ "Hookshot_Pull_B",
	/* 306 */ "Hookshot_TakeAim",
	/* 307 */ "Hookshot_StandbyWalkL",
	/* 308 */ "Hookshot_StandbyWalkR",
	/* 309 */ "Hookshot_StandbyWalkSlowR",
	/* 310 */ "Hookshot_AimIdle",
	/* 311 */ "Hookshot_Shoot",
	/* 312 */ "Cs_Ganon_Finish",
	/* 313 */ "Cs_Ganon_FinishPullSword",
	/* 314 */ "Nayru_A",
	/* 315 */ "Nayru_B",
	/* 316 */ "Nayru_C",
	/* 317 */ "Farore_B",
	/* 318 */ "Farore_C",
	/* 319 */ "Farore_D",
	/* 320 */ "Din_B",
	/* 321 */ "Din_C",
	/* 322 */ "Din_D",
	/* 323 */ "FaroreDin_A",
	/* 324 */ "Unused_Magic_Cancel",
	/* 325 */ NULL,
	/* 326 */ NULL,
	/* 327 */ NULL,
	/* 328 */ NULL,
	/* 329 */ "Turn_1H",
	/* 330 */ "Turn_Normal",
	/* 331 */ NULL,
	/* 332 */ NULL,
	/* 333 */ NULL,
	/* 334 */ NULL,
	/* 335 */ NULL,
	/* 336 */ NULL,
	/* 337 */ NULL,
	/* 338 */ NULL,
	/* 339 */ NULL,
	/* 340 */ NULL,
	/* 341 */ NULL,
	/* 342 */ NULL,
	/* 343 */ NULL,
	/* 344 */ NULL,
	/* 345 */ NULL,
	/* 346 */ NULL,
	/* 347 */ NULL,
	/* 348 */ NULL,
	/* 349 */ NULL,
	/* 350 */ "Hold_PickUp_Medium",
	/* 351 */ "Hold_PickUp_Small",
	/* 352 */ "Hold_HoldAboveHead",
	/* 353 */ NULL,
	/* 354 */ NULL,
	/* 355 */ NULL,
	/* 356 */ NULL,
	/* 357 */ NULL,
	/* 358 */ NULL,
	/* 359 */ NULL,
	/* 360 */ NULL,
	/* 361 */ NULL,
	/* 362 */ NULL,
	/* 363 */ NULL,
	/* 364 */ NULL,
	/* 365 */ NULL,
	/* 366 */ NULL,
	/* 367 */ NULL,
	/* 368 */ NULL,
	/* 369 */ NULL,
	/* 370 */ NULL,
	/* 371 */ NULL,
	/* 372 */ NULL,
	/* 373 */ NULL,
	/* 374 */ NULL,
	/* 375 */ NULL,
	/* 376 */ NULL,
	/* 377 */ NULL,
	/* 378 */ NULL,
	/* 379 */ NULL,
	/* 380 */ NULL,
	/* 381 */ NULL,
	/* 382 */ "Hurt_Electified",
	/* 383 */ "Death_Electified",
	/* 384 */ NULL,
	/* 385 */ NULL,
	/* 386 */ NULL,
	/* 387 */ NULL,
	/* 388 */ "Pocket_SwordShield",
	/* 389 */ "Pocket_Explosive",
	/* 390 */ "Pocket_UnequipSwordOnly",
	/* 391 */ "Pocket_UnequipLeftHand",
	/* 392 */ "Pocket_UnequipRightHand",
	/* 393 */ NULL,
	/* 394 */ NULL,
	/* 395 */ NULL,
	/* 396 */ NULL,
	/* 397 */ NULL,
	/* 398 */ NULL,
	/* 399 */ NULL,
	/* 400 */ NULL,
	/* 401 */ NULL,
	/* 402 */ NULL,
	/* 403 */ NULL,
	/* 404 */ NULL,
	/* 405 */ "Bonk_1H",
	/* 406 */ "Bonk_Normal",
	/* 407 */ "Bonk_2H",
	/* 408 */ NULL,
	/* 409 */ NULL,
	/* 410 */ NULL,
	/* 411 */ NULL,
	/* 412 */ NULL,
	/* 413 */ NULL,
	/* 414 */ NULL,
	/* 415 */ NULL,
	/* 416 */ NULL,
	/* 417 */ NULL,
	/* 418 */ NULL,
	/* 419 */ NULL,
	/* 420 */ "Roll_1H",
	/* 421 */ "Roll_Normal",
	/* 422 */ NULL,
	/* 423 */ "Dekunut_A",
	/* 424 */ "Dekunut_B",
	/* 425 */ "Pocket_Explosive2",
	/* 426 */ NULL,
	/* 427 */ NULL,
	/* 428 */ NULL,
	/* 429 */ "Pocket_Explosive3",
	/* 430 */ "Pocket_UnequipSwordShield",
	/* 431 */ "Pocket_Equip2HSword",
	/* 432 */ "Pocket_Unk_432",
	/* 433 */ "Pocket_UnequipOcarina",
	/* 434 */ "Pocket_EquipOcarina",
	/* 435 */ "PlayOcarina",
	/* 436 */ NULL,
	/* 437 */ NULL,
	/* 438 */ NULL,
	/* 439 */ NULL,
	/* 440 */ NULL,
	/* 441 */ NULL,
	/* 442 */ NULL,
	/* 443 */ NULL,
	/* 444 */ NULL,
	/* 445 */ NULL,
	/* 446 */ NULL,
	/* 447 */ NULL,
	/* 448 */ "Hold_PutDown_Medium",
	/* 449 */ "Hold_PutDown_Small",
	/* 450 */ "Hurt_ReDead_A",
	/* 451 */ "Hurt_ReDead_B",
	/* 452 */ NULL,
	/* 453 */ NULL,
	/* 454 */ NULL,
	/* 455 */ NULL,
	/* 456 */ NULL,
	/* 457 */ NULL,
	/* 458 */ NULL,
	/* 459 */ NULL,
	/* 460 */ NULL,
	/* 461 */ NULL,
	/* 462 */ NULL,
	/* 463 */ NULL,
	/* 464 */ NULL,
	/* 465 */ NULL,
	/* 466 */ "Speak_A",
	/* 467 */ "Speak_B",
	/* 468 */ "Speak_LookingUp_A",
	/* 469 */ "Speak_LookingUp_B",
	/* 470 */ "Hold_Throw_1H",
	/* 471 */ "Hold_Throw_Normal",
	/* 472 */ NULL,
	/* 473 */ NULL,
	/* 474 */ NULL,
	/* 475 */ NULL,
	/* 476 */ NULL,
	/* 477 */ NULL,
	/* 478 */ "Idle_LookAround_Normal",
	/* 479 */ "Idle_Hot_Normal",
	/* 480 */ "Idle_Cold_Normal",
	/* 481 */ NULL,
	/* 482 */ NULL,
	/* 483 */ NULL,
	/* 484 */ NULL,
	/* 485 */ "Stand_1H",
	/* 486 */ "Stand_Normal",
	/* 487 */ "Idle_LookAround_1H",
	/* 488 */ "Idle_Hot_1H",
	/* 489 */ "Idle_Cold_1H",
	/* 490 */ NULL,
	/* 491 */ NULL,
	/* 492 */ NULL,
	/* 493 */ NULL,
	/* 494 */ NULL,
	/* 495 */ NULL,
	/* 496 */ NULL,
	/* 497 */ NULL,
	/* 498 */ NULL,
	/* 499 */ NULL,
	/* 500 */ NULL,
	/* 501 */ NULL,
	/* 502 */ NULL,
	/* 503 */ NULL,
	/* 504 */ NULL,
	/* 505 */ NULL,
	/* 506 */ NULL,
	/* 507 */ NULL,
	/* 508 */ NULL,
	/* 509 */ NULL,
	/* 510 */ NULL,
	/* 511 */ NULL,
	/* 512 */ "Death_Drown",
	/* 513 */ NULL,
	/* 514 */ NULL,
	/* 515 */ NULL,
	/* 516 */ NULL,
	/* 517 */ NULL,
	/* 518 */ NULL,
	/* 519 */ NULL,
	/* 520 */ NULL,
	/* 521 */ NULL,
	/* 522 */ NULL,
	/* 523 */ NULL,
	/* 524 */ NULL,
	/* 525 */ NULL,
	/* 526 */ NULL,
	/* 527 */ NULL,
	/* 528 */ NULL,
	/* 529 */ NULL,
	/* 530 */ NULL,
	/* 531 */ NULL,
	/* 532 */ NULL,
	/* 533 */ NULL,
	/* 534 */ NULL,
	/* 535 */ NULL,
	/* 536 */ NULL,
	/* 537 */ NULL,
	/* 538 */ "Idle_AdjustTunic_Normal",
	/* 539 */ "Idle_KickBoots_Normal",
	/* 540 */ "Idle_Yawn_Normal",
	/* 541 */ NULL,
	/* 542 */ NULL,
	/* 543 */ "Idle_AdjustTunic_1H",
	/* 544 */ "Idle_KickBoots_1H",
	/* 545 */ "Idle_SpinTheShield_1H",
	/* 546 */ "Idle_SwingSword_1H",
	/* 547 */ "Idle_SwingSword_2H",
	/* 548 */ "Idle_Yawn_1H",
	/* 549 */ NULL,
	/* 550 */ NULL,
	/* 551 */ NULL,
	/* 552 */ NULL,
	/* 553 */ NULL,
	/* 554 */ NULL,
	/* 555 */ NULL,
	/* 556 */ NULL,
	/* 557 */ NULL,
	/* 558 */ NULL,
	/* 559 */ NULL,
	/* 560 */ NULL,
	/* 561 */ NULL,
	/* 562 */ NULL,
	/* 563 */ NULL,
	/* 564 */ NULL,
	/* 565 */ NULL,
	/* 566 */ NULL,
	/* 567 */ NULL,
	/* 568 */ NULL,
	/* 569 */ NULL,
	/* 570 */ NULL,
	/* 571 */ NULL,
	/* 572 */ NULL,
};